{% set name = "historydag" %}
{% set version = "1.3.1" %}
{% set python_min = "3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f93c652756a7a39383d3a8df1e47c3ec5b820cea8e7c0caea6cd4a39484d895e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - frozendict
    - six
    - pyqt
    - ete3
    - biopython
    - python-graphviz
    - protobuf

test:
  imports:
    - historydag
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://matsengrp.github.io/historydag
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: A basic history DAG implementation
  description: |
    Historydag is a basic history DAG implementation for Python 3.7+
    written in pure Python. A history DAG object compactly expresses
    a collection of internally labeled trees.
  doc_url: https://matsengrp.github.io/historydag
  dev_url: https://github.com/matsengrp/historydag

extra:
  recipe-maintainers:
    - willdumm
